name: Pull and Deploy Docker Image
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]
    # branches: ['**']


jobs:
  get_version:
    uses: ./.github/workflows/get-formated-tag.yml
    with:
      DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"

  deploy:
    runs-on: [self-hosted, virtualbox]
    needs: get_version
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Login to Docker registry
        id: login_docker
        run: |
          echo "Logging in to Docker registry"
          docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Docker image
        id: pull_image
        run: |
          echo "Pulling Docker image with tag: ${{ needs.get_version.outputs.full_tag }}"
          docker pull ${{ needs.get_version.outputs.full_tag }}
        shell: bash

      - name: Run Docker container
        id: run_container
        run: |
          echo "Running Docker container with tag: ${{ needs.get_version.outputs.full_tag }}"
          echo "CONTAINER_ID=$(docker run -d -p 8022:8080 ${{ needs.get_version.outputs.full_tag }})" >> $GITHUB_ENV
        shell: bash

      - name: Check with curl nginx
        id: check_nginx
        run: |
          echo "Checking if nginx is running"
          for i in {1..10}; do curl -I http://localhost:8022 && break || sleep 5; done
          curl -I http://localhost:8022
        shell: bash

      - name: Delete Docker Container and Image
        id: delete_container_image
        run: |
          echo "Deleting Docker container and image"
          docker stop ${{ env.CONTAINER_ID }}
          docker rm ${{ env.CONTAINER_ID }}
          docker rmi ${{ needs.get_version.outputs.full_tag }}
        shell: bash

      - name: Logout from Docker
        if: always()
        run: |
          echo "Logging out from Docker registry"
          docker logout
        shell: bash