name: Build and Push Docker Image
on: [push,workflow_dispatch]

jobs:
  get_version:
    uses: ./.github/workflows/get-formated-tag.yml
    with:
      DOCKER_USERNAME: "${{ vars.DOCKER_USERNAME }}"

  build:
    runs-on: [self-hosted, labs-runner]
    needs: get_version

    steps:
      - name: Debug - mostrar tag recibido desde reusable workflow
        run: |
          echo "📦 Tag recibido desde reusable workflow: '${{ needs.get_version.outputs.full_tag }}'"
        shell: bash
    

      - name: Login to Docker registry
        id: login_docker
        run: |
          echo "Logging in to Docker registry"
          # docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        shell: bash

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        id: build_image
        run: |
          echo "Building Docker image with tag: ${{ needs.get_version.outputs.full_tag }}"
          # docker build -t ${{ needs.get_version.outputs.full_tag }} .
        shell: bash

      - name: Show list of images
        id: list_images
        run: |
          echo "Listing Docker images"
          docker images
        shell: bash

      - name: Push Docker image
        id: push_image
        run: |
          echo "Pushing Docker image with tag: ${{ needs.get_version.outputs.full_tag }}"
          # docker push ${{ needs.get_version.outputs.full_tag }}
        shell: bash

      - name: Is Valid
        run: |
          echo "${{ needs.get_version.outputs.full_tag }}"
          if [[ "${{ needs.get_version.outputs.full_tag }}" == 'spatrocinio/sample-angular-app:0.0.0' ]]; then
            echo "Valid"
          else
            echo "Invalid"
          fi